[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  functionsPort = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
